export const books = [
	{
		id: "A0001",
		title: "Don't Go There",
		author: "jane austen",
		genres: ["adventure", "thriller", "mystery"],
		image: require("./books/dont_go_there.png").default,
		price: 69.9,
		synopsis: {
			short: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam varius non lectus vitae eleifend. Donec pretium gravida suscipit. Maecenas ipsum sapien, aliquet eget leo.",
			long: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc ut consequat leo. Morbi viverra egestas nibh vel aliquet. Nullam tincidunt elit nec elit porta, non dictum mauris laoreet. Curabitur nec maximus augue. Praesent lobortis justo odio, ut gravida nisl bibendum a. Curabitur et auctor lorem. Suspendisse vitae ligula et lacus elementum sodales non et magna. Sed gravida, nibh non mollis rhoncus, nisl nulla tristique purus, laoreet laoreet tortor purus ac mi. Aliquam et dolor malesuada, faucibus libero vel, venenatis est. Donec quis dolor ac felis feugiat sodales. Cras consequat, justo et imperdiet pharetra, nisi turpis varius ex, commodo luctus risus. ",
		},
		is_special: 0,
		is_recommended: 0,
		is_popular: 0,
		is_bestselling: true,
		is_flashsale: 0,
		is_onsale: 0,
		is_featured: 0,
	},
	{
		id: "A0002",
		title: "Foul Play",
		author: "Honoré de Balzac",
		genres: ["thriller", "mystery", "western"],
		image: require("./books/foul_play.png").default,
		price: 69.9,
		synopsis: {
			short: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam varius non lectus vitae eleifend. Donec pretium gravida suscipit. Maecenas ipsum sapien, aliquet eget leo.",
			long: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc ut consequat leo. Morbi viverra egestas nibh vel aliquet. Nullam tincidunt elit nec elit porta, non dictum mauris laoreet. Curabitur nec maximus augue. Praesent lobortis justo odio, ut gravida nisl bibendum a. Curabitur et auctor lorem. Suspendisse vitae ligula et lacus elementum sodales non et magna. Sed gravida, nibh non mollis rhoncus, nisl nulla tristique purus, laoreet laoreet tortor purus ac mi. Aliquam et dolor malesuada, faucibus libero vel, venenatis est. Donec quis dolor ac felis feugiat sodales. Cras consequat, justo et imperdiet pharetra, nisi turpis varius ex, commodo luctus risus. ",
		},
		is_special: 0,
		is_recommended: 0,
		is_popular: 0,
		is_bestselling: 0,
		is_flashsale: 0,
		is_onsale: 0,
		is_featured: 0,
	},
	{
		id: "A0003",
		title: "Lost In The Woods",
		author: "stendhal",
		genres: ["thriller", "adventure", "western"],
		image: require("./books/lost_in_the_woods.png").default,
		price: 69.9,
		synopsis: {
			short: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam varius non lectus vitae eleifend. Donec pretium gravida suscipit. Maecenas ipsum sapien, aliquet eget leo.",
			long: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc ut consequat leo. Morbi viverra egestas nibh vel aliquet. Nullam tincidunt elit nec elit porta, non dictum mauris laoreet. Curabitur nec maximus augue. Praesent lobortis justo odio, ut gravida nisl bibendum a. Curabitur et auctor lorem. Suspendisse vitae ligula et lacus elementum sodales non et magna. Sed gravida, nibh non mollis rhoncus, nisl nulla tristique purus, laoreet laoreet tortor purus ac mi. Aliquam et dolor malesuada, faucibus libero vel, venenatis est. Donec quis dolor ac felis feugiat sodales. Cras consequat, justo et imperdiet pharetra, nisi turpis varius ex, commodo luctus risus. ",
		},
		is_special: 0,
		is_recommended: 0,
		is_popular: 0,
		is_bestselling: true,
		is_flashsale: 0,
		is_onsale: 0,
		is_featured: 0,
	},
	{
		id: "A0004",
		title: "Murdering Last Summer",
		author: "Herman Melville",
		genres: ["thriller", "mystery", "horror"],
		image: require("./books/murdering_last_summer.png").default,
		price: 69.9,
		synopsis: {
			short: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam varius non lectus vitae eleifend. Donec pretium gravida suscipit. Maecenas ipsum sapien, aliquet eget leo.",
			long: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc ut consequat leo. Morbi viverra egestas nibh vel aliquet. Nullam tincidunt elit nec elit porta, non dictum mauris laoreet. Curabitur nec maximus augue. Praesent lobortis justo odio, ut gravida nisl bibendum a. Curabitur et auctor lorem. Suspendisse vitae ligula et lacus elementum sodales non et magna. Sed gravida, nibh non mollis rhoncus, nisl nulla tristique purus, laoreet laoreet tortor purus ac mi. Aliquam et dolor malesuada, faucibus libero vel, venenatis est. Donec quis dolor ac felis feugiat sodales. Cras consequat, justo et imperdiet pharetra, nisi turpis varius ex, commodo luctus risus. ",
		},
		is_special: 0,
		is_recommended: 0,
		is_popular: 0,
		is_bestselling: 0,
		is_flashsale: 0,
		is_onsale: 0,
		is_featured: 0,
	},
	{
		id: "A0005",
		title: "The Andromeda Boy",
		author: "Muhamad Amir",
		genres: ["thriller", "romantic", "young adult"],
		image: require("./books/the_andromeda_boy.png").default,
		price: 69.9,
		synopsis: {
			short: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam varius non lectus vitae eleifend. Donec pretium gravida suscipit. Maecenas ipsum sapien, aliquet eget leo.",
			long: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc ut consequat leo. Morbi viverra egestas nibh vel aliquet. Nullam tincidunt elit nec elit porta, non dictum mauris laoreet. Curabitur nec maximus augue. Praesent lobortis justo odio, ut gravida nisl bibendum a. Curabitur et auctor lorem. Suspendisse vitae ligula et lacus elementum sodales non et magna. Sed gravida, nibh non mollis rhoncus, nisl nulla tristique purus, laoreet laoreet tortor purus ac mi. Aliquam et dolor malesuada, faucibus libero vel, venenatis est. Donec quis dolor ac felis feugiat sodales. Cras consequat, justo et imperdiet pharetra, nisi turpis varius ex, commodo luctus risus. ",
		},
		is_special: 0,
		is_recommended: 0,
		is_popular: 0,
		is_bestselling: 0,
		is_flashsale: 0,
		is_onsale: 0,
		is_featured: 0,
	},
	{
		id: "A0006",
		title: "The Black Woods",
		author: "William Shakespeare",
		genres: ["thriller", "drama", "mystery"],
		image: require("./books/the_black_woods.png").default,
		price: 69.9,
		synopsis: {
			short: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam varius non lectus vitae eleifend. Donec pretium gravida suscipit. Maecenas ipsum sapien, aliquet eget leo.",
			long: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc ut consequat leo. Morbi viverra egestas nibh vel aliquet. Nullam tincidunt elit nec elit porta, non dictum mauris laoreet. Curabitur nec maximus augue. Praesent lobortis justo odio, ut gravida nisl bibendum a. Curabitur et auctor lorem. Suspendisse vitae ligula et lacus elementum sodales non et magna. Sed gravida, nibh non mollis rhoncus, nisl nulla tristique purus, laoreet laoreet tortor purus ac mi. Aliquam et dolor malesuada, faucibus libero vel, venenatis est. Donec quis dolor ac felis feugiat sodales. Cras consequat, justo et imperdiet pharetra, nisi turpis varius ex, commodo luctus risus. ",
		},
		is_special: 0,
		is_recommended: 0,
		is_popular: 0,
		is_bestselling: 0,
		is_flashsale: 0,
		is_onsale: 0,
		is_featured: 0,
	},
	{
		id: "A0007",
		title: "The Dark Side of Winter",
		author: "Henry Fielding",
		genres: ["thriller", "adventure", "mystery"],
		image: require("./books/the_dark_side_of_winter.png").default,
		price: 69.9,
		synopsis: {
			short: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam varius non lectus vitae eleifend. Donec pretium gravida suscipit. Maecenas ipsum sapien, aliquet eget leo.",
			long: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc ut consequat leo. Morbi viverra egestas nibh vel aliquet. Nullam tincidunt elit nec elit porta, non dictum mauris laoreet. Curabitur nec maximus augue. Praesent lobortis justo odio, ut gravida nisl bibendum a. Curabitur et auctor lorem. Suspendisse vitae ligula et lacus elementum sodales non et magna. Sed gravida, nibh non mollis rhoncus, nisl nulla tristique purus, laoreet laoreet tortor purus ac mi. Aliquam et dolor malesuada, faucibus libero vel, venenatis est. Donec quis dolor ac felis feugiat sodales. Cras consequat, justo et imperdiet pharetra, nisi turpis varius ex, commodo luctus risus. ",
		},
		is_special: 0,
		is_recommended: 0,
		is_popular: 0,
		is_bestselling: 0,
		is_flashsale: 0,
		is_onsale: 0,
		is_featured: 0,
	},
	{
		id: "A0008",
		title: "The Heist",
		author: "Charles Dickens",
		genres: ["thriller", "adventure", "action"],
		image: require("./books/the_heist.png").default,
		price: 69.9,
		synopsis: {
			short: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam varius non lectus vitae eleifend. Donec pretium gravida suscipit. Maecenas ipsum sapien, aliquet eget leo.",
			long: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc ut consequat leo. Morbi viverra egestas nibh vel aliquet. Nullam tincidunt elit nec elit porta, non dictum mauris laoreet. Curabitur nec maximus augue. Praesent lobortis justo odio, ut gravida nisl bibendum a. Curabitur et auctor lorem. Suspendisse vitae ligula et lacus elementum sodales non et magna. Sed gravida, nibh non mollis rhoncus, nisl nulla tristique purus, laoreet laoreet tortor purus ac mi. Aliquam et dolor malesuada, faucibus libero vel, venenatis est. Donec quis dolor ac felis feugiat sodales. Cras consequat, justo et imperdiet pharetra, nisi turpis varius ex, commodo luctus risus. ",
		},
		is_special: 0,
		is_recommended: 0,
		is_popular: 0,
		is_bestselling: true,
		is_flashsale: 0,
		is_onsale: 0,
		is_featured: 0,
	},
	{
		id: "A0009",
		title: "The Watcher in the Woods",
		author: "Emily Bronte",
		genres: ["thriller", "adventure", "young adult"],
		image: require("./books/the_watcher_in_the_woods.png").default,
		price: 69.9,
		synopsis: {
			short: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam varius non lectus vitae eleifend. Donec pretium gravida suscipit. Maecenas ipsum sapien, aliquet eget leo.",
			long: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc ut consequat leo. Morbi viverra egestas nibh vel aliquet. Nullam tincidunt elit nec elit porta, non dictum mauris laoreet. Curabitur nec maximus augue. Praesent lobortis justo odio, ut gravida nisl bibendum a. Curabitur et auctor lorem. Suspendisse vitae ligula et lacus elementum sodales non et magna. Sed gravida, nibh non mollis rhoncus, nisl nulla tristique purus, laoreet laoreet tortor purus ac mi. Aliquam et dolor malesuada, faucibus libero vel, venenatis est. Donec quis dolor ac felis feugiat sodales. Cras consequat, justo et imperdiet pharetra, nisi turpis varius ex, commodo luctus risus. ",
		},
		is_special: 0,
		is_recommended: 0,
		is_popular: 0,
		is_bestselling: 0,
		is_flashsale: 0,
		is_onsale: 0,
		is_featured: 0,
	},
	{
		id: "A0010",
		title: "When the Clock Strikes Eight",
		author: "Gustave Flaubert",
		genres: ["thriller", "adventure", "science fiction"],
		image: require("./books/when_the_clock_strikes_eight.png").default,
		price: 69.9,
		synopsis: {
			short: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam varius non lectus vitae eleifend. Donec pretium gravida suscipit. Maecenas ipsum sapien, aliquet eget leo.",
			long: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc ut consequat leo. Morbi viverra egestas nibh vel aliquet. Nullam tincidunt elit nec elit porta, non dictum mauris laoreet. Curabitur nec maximus augue. Praesent lobortis justo odio, ut gravida nisl bibendum a. Curabitur et auctor lorem. Suspendisse vitae ligula et lacus elementum sodales non et magna. Sed gravida, nibh non mollis rhoncus, nisl nulla tristique purus, laoreet laoreet tortor purus ac mi. Aliquam et dolor malesuada, faucibus libero vel, venenatis est. Donec quis dolor ac felis feugiat sodales. Cras consequat, justo et imperdiet pharetra, nisi turpis varius ex, commodo luctus risus. ",
		},
		is_special: 0,
		is_recommended: 0,
		is_popular: 0,
		is_bestselling: 0,
		is_flashsale: 0,
		is_onsale: 0,
		is_featured: 0,
	},
];
